### PR TITLE
Adding Anna.Json library

### PR DESCRIPTION
**Pull request by ipjohnson**
I've added a couple extension methods that make it easier to send and receive JSON objects. I also updated the build and added a new nuspec file.

// Get T using UriArguements, QueryString and Json POST data 
public static T GetAs&lt;T&gt;(this RequestContext ctx)

// Respond to request with a strong typed instance
public static void RespondAs&lt;T&gt;(this RequestContext requestContext, T tReturn, int statusCode = 200, IDictionary<string, string> headers = null)

// Subscribe handler that takes a strongly typed model
public static IDisposable SubscribeAslt;T&gt;(this IObservable<RequestContext> queryable, Action<T> handler)

// Subscribe handler that takes strongly typed model and returns strongly typed model
public static IDisposable SubscribeAs&lt;T,TReturn&gt;(this IObservable<RequestContext> queryable, Func<T,TReturn> handler)

### CODE REVIEW

**Comment by kawazoe** [comment]
This looks interesting, though it would be nice if those extensions would not be bound to a specific serializer. Json.NET is known to be the most popular, but not the fastest and not that good at dealing with the LoH.

**Comment by jfromaniello** [comment]
I really like where this is going well done. 

Not sure about the extension method names.. I'd prefer something more specific instead of `req.GetAs<Person>` maybe `req.GetBodyAs<Person>`  or something like that.

@kawazoe  Regarding the serializers, you will have to excuse me I haven't been doing .Net in a long time now, and I don't know the current state. Maybe using the one that comes with .net as default?

**Comment by kawazoe** [comment]
@jfromaniello Not necessarily. My point is that the choice should be left to the user. Anna should not impose a specific implementation to serialize the data. If the users wants to use the build in serializers, they should be able to. If they want to use [Json.NET](http://james.newtonking.com/json), [FastJSON](http://www.codeproject.com/Articles/159450/fastJSON) or maybe even the [Daishi.Microservices.Component.Serialization](https://github.com/daishisystems/Daishi.Microservices) library, they should also be able to.

Also, since you mentioned naming, considering that none of the method names directly implies json serialization, maybe the user might want to use them with other kinds of serializers like an XML serializer or a binary serializer.

**Comment by jfromaniello** [comment]
Yes, I understand.. rough idea maybe we can have an interface like:

```
server.RegisterSerializer('json', Anna.JsonNetSerializer);
server.RegisterSerializer('xml', Anna.XmlSerializer);
```

and `request.GetBody<Person>()` uses the `Content-Type` header.

@kawazoe  Is this the kind of api you are looking for?

**Comment by kawazoe** [comment]
Yes, pretty much. Also, I really like the idea of using the `Content-Type` header.

**Comment by ipjohnson** [comment]
So something that might have been over looked is that it's not just getting values from the body. It's also getting values from the QueryString and UriArguements. The Json.Net library offers a JObject that does all of the heavy lifting for you. 

So while deserializing the body is relatively easy it becomes much harder if you want to mix in the other parts of the request. For what I'm doing I happen to really like the mix in especially when looking to have a strong type for GET where there is no body.

I do like the ideas you guys are throwing out but I actually don't have much time I can give towards this project.

Would it be possible to just implement the small change to the ArgumentsDynamic class the add the IEnumerable<KeyValuePair<string,string>> interface. That way it makes it easier for someone to do what I'm doing?

**Comment by kawazoe** [comment]
Well, I have a lot of time on my hands so I could implement this whole thing in a fork and submit a new pull request later this week (if that's ok with you @jfromaniello ?).

As for ArgumentDynamics, I don't see any problem in doing this now if we are to build on your idea. As a disclaimer, I am just a user and not a collaborator yet so that is to be taken with a grain of salt.

**Comment by ipjohnson** [comment]
With that in mind may I suggest this PR gets closed and @kawazoe can take a stab at a more flexible implementation.

I can do a separate PR for the ArguementDynamics change or wait for the change from @kawazoe. It's up to you guys.

thanks
-Ian

**Comment by jfromaniello** [comment]
Thank you guys for this discussion, I think it has been really useful!

so yes, lets way to @kawazoe 

I am very thankfully how you guys are taking this to the next level,
Maybe we should put this repository under an github organisation?

**Comment by kawazoe** [comment]
That will definitely help to improve the visibility of the serialization utilities. Is it ok if I let you setup the repo for the `Anna.Serialization.NewtonsoftJson`? That way you'll be able to add it to your AppVeyor account and get nuget publishing running.

**Pull request closed without merging**
